export { default as InstaIcon } from "./instagram.svg";
export { default as YoutubeIcon } from "./youtube.svg";
export { default as EmptyHeart } from "./emptyHeart.svg";
export { default as FaceBookIcon } from "./facebook.svg";
export { default as HeartIcon } from "./heart.svg";
export { default as LogoIcon } from "./logo.svg";
export { default as searchIcon } from "./search.svg";
export { default as Bomi } from "./bomi.svg";
export { default as AcornIcon } from "./acorn.svg";
